version: "3.1"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root0
      TZ: "Asia/Seoul"
    ports:
      - 3306:3306
